name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build UI
      run: |
        ls -al
        cd ui
        ls -al
        npm i
        npm run build
    - name: Build go server
      run: |
        go mod tidy
        go build cmd/main.go
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag divulge-keyvalue-db-ui:$(date +%s)
